# Generated by Django 5.1.4 on 2025-01-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.SmallAutoField(editable=False, help_text='Id of the blog', primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='Title of the blog', max_length=255)),
                ('description', models.CharField(help_text='Description of the blog: typically a short, concise hook', max_length=255)),
                ('starred', models.BooleanField(help_text='True/False for whether the blog is starred/pinned')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The creation date-time of the blog')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The last modified date-time of the blog')),
                ('content', models.TextField(help_text='The html (not react jsx) content of the blog. This does not contain images, but links to the images when develiered')),
                ('image', models.ImageField(help_text='The path to the image in the MEDIA folder of Django', upload_to='blogs/images')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.SmallAutoField(editable=False, help_text='Id of the project', primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='Title of the project', max_length=255)),
                ('description', models.CharField(help_text='Description of the project: typically a short, concise hook', max_length=255)),
                ('starred', models.BooleanField(help_text='True/False for whether the project is starred/pinned')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The creation date-time of the project')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The last modified date-time of the project')),
                ('content', models.TextField(help_text='The html (not react jsx) content of the project. This does not contain images, but links to the images when develiered')),
                ('image', models.ImageField(help_text='The path to the image in the MEDIA folder of Django', upload_to='projects/images')),
            ],
        ),
    ]
