# Generated by Django 5.1.4 on 2025-01-15 02:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='published',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 1, 15, 7, 0, tzinfo=datetime.timezone.utc), help_text='The publsih time of the blog'),
        ),
    ]
