# Generated by Django 5.1.4 on 2025-02-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_session_alter_blog_published_alter_project_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.AutoField(db_comment='Session id int created by backend and given to frontend', editable=False, primary_key=True, serialize=False),
        ),
    ]
