# Generated by Django 5.1.4 on 2025-02-06 16:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('session_id', models.AutoField(db_comment='Session id int created by backend and given to frontend', editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Start time of the session')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.UUIDField(db_comment='UUID to track a user in the cookies/local storage', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Start time of the session')),
            ],
        ),
        migrations.AlterField(
            model_name='articleanalytics',
            name='session',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.sessions'),
        ),
        migrations.AlterField(
            model_name='linkstaken',
            name='session',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.sessions'),
        ),
        migrations.AlterField(
            model_name='pageanalytics',
            name='session',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.sessions'),
        ),
        migrations.AlterField(
            model_name='referredfrom',
            name='session',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.sessions'),
        ),
        migrations.AddField(
            model_name='sessions',
            name='user_id',
            field=models.ForeignKey(db_comment='id of the user', editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
