# Generated by Django 5.1.4 on 2025-02-06 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_sessions_users_alter_articleanalytics_session_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sessions',
            new_name='Session',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
