# Generated by Django 5.1.4 on 2025-02-06 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_sessions_session_rename_users_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleAnalytics',
            new_name='ArticleAnalytic',
        ),
        migrations.RenameModel(
            old_name='PageAnalytics',
            new_name='PageAnalytic',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='user_id',
            new_name='user',
        ),
    ]
