# Generated by Django 5.1.4 on 2025-02-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_articleanalytics_articleanalytic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageanalytic',
            name='page',
            field=models.PositiveSmallIntegerField(choices=[(1, 'home'), (2, 'blogs'), (3, 'projects'), (4, 'blog'), (5, 'projects'), (6, 'analytics')], db_comment="The page viewed ['home', 'blogs', 'projects']", default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.AutoField(db_comment='Session id int created by backend and given to frontend', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
