# Generated by Django 5.1.4 on 2025-02-06 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_pageanalytic_page_alter_session_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkstaken',
            name='session',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.session'),
        ),
    ]
