# Generated by Django 5.1.4 on 2025-02-07 22:42

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_linkstaken_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleanalytic',
            name='article_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'blog'), (2, 'project')], db_comment="The link taken ['unknown', 'blog', 'project']", default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 2, 8, 7, 0, tzinfo=datetime.timezone.utc), help_text='The publish time of the blog'),
        ),
        migrations.AlterField(
            model_name='linkstaken',
            name='link',
            field=models.PositiveSmallIntegerField(choices=[(1, 'LinkedIn'), (2, 'YouTube'), (3, 'GitHub')], db_comment="The link taken ['LinkedIn', 'YouTube', 'GitHub']", default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='pageanalytic',
            name='page',
            field=models.PositiveSmallIntegerField(choices=[(1, 'home'), (2, 'blogs'), (3, 'projects'), (4, 'blog'), (5, 'project'), (6, 'analytics')], db_comment="The page viewed ['home', 'blogs', 'projects']", default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='published',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 2, 8, 7, 0, tzinfo=datetime.timezone.utc), help_text='The publish time of the project'),
        ),
        migrations.AlterField(
            model_name='referredfrom',
            name='link',
            field=models.PositiveSmallIntegerField(choices=[(1, 'LinkedIn'), (2, 'YouTube'), (3, 'GitHub')], db_comment="The link referred from ['LinkedIn', 'YouTube', 'GitHub']", default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.UUIDField(db_comment='UUID created by backend and given to frontend to track current session, expires after a day', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='user',
            field=models.ForeignKey(db_comment='the user of the session', editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
