# Generated by Django 5.1.4 on 2025-02-09 19:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_articleanalytic_article_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleanalytic',
            name='session',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.session'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 2, 10, 7, 0, tzinfo=datetime.timezone.utc), help_text='The publish time of the blog'),
        ),
        migrations.AlterField(
            model_name='pageanalytic',
            name='session',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.session'),
        ),
        migrations.AlterField(
            model_name='project',
            name='published',
            field=models.DateTimeField(db_default=datetime.datetime(2025, 2, 10, 7, 0, tzinfo=datetime.timezone.utc), help_text='The publish time of the project'),
        ),
        migrations.AlterField(
            model_name='referredfrom',
            name='session',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.session'),
        ),
    ]
